apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: detection1
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 300s
    spec:
      containers:
      - image: docker.io/mc0137/detect_abnormal:v1.7@sha256:7b7517c76c946f662087abdde5c296599dc393cf522be60a76f28840cfbf88d4
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: worker2.kn
